Daggerpov/Spawn-App-iOS-SwiftUI

Spawn-App-iOS-SwiftUI/Models/Event.swift
Spawn-App-iOS-SwiftUI/Views/ContentView.swift
Spawn-App-iOS-SwiftUI/Views/EventView.swift

Fixed event card spacing

---

.gitignore
README.md
Spawn-App-iOS-SwiftUI/Models/AppUser.swift
Spawn-App-iOS-SwiftUI/Models/ChatMessage.swift
Spawn-App-iOS-SwiftUI/Models/Event.swift
Spawn-App-iOS-SwiftUI/Models/FriendTag.swift
Spawn-App-iOS-SwiftUI/Models/Location.swift
Spawn-App-iOS-SwiftUI/Models/User.swift
Spawn-App-iOS-SwiftUI/Models/entity-relationship-diagram.dbml

Added Entity Relationship Diagram + Investigated Struct->Class for models

---

Spawn-App-iOS-SwiftUI/Views/ContentView.swift

removed useless comment on ContentView

---

Spawn-App-iOS-SwiftUI.xcodeproj/project.pbxproj
Spawn-App-iOS-SwiftUI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Spawn-App-iOS-SwiftUI/ViewModels/EventCardViewModel.swift
Spawn-App-iOS-SwiftUI/Views/EventCardView.swift
Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/ParticipantsImagesView.swift
Spawn-App-iOS-SwiftUI/Views/ViewModifiers/ProfileImages.swift

#25 #22 #26
- Created pop-up for event description
- Created logic for toggling event participation button
- Refactored into `EventViews` for re-use of components between `EventCardView` and `EventDescriptionView`
- Event Card/Description participation profile images improvements:
- Ensured ordering of creator before other participants, and that the creator is always included
- Ensured no duplicates, even if `event.creator` in `event.participants`

Event Description Modal (#22)

---

Spawn-App-iOS-SwiftUI/Models/AppUser.swift
Spawn-App-iOS-SwiftUI/Models/FriendTag.swift
Spawn-App-iOS-SwiftUI/Models/User.swift
Spawn-App-iOS-SwiftUI/Services/AppUserService.swift
Spawn-App-iOS-SwiftUI/Services/NameFormatterService.swift
Spawn-App-iOS-SwiftUI/ViewModels/FriendListingViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/FriendsListViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/TagsListViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Enums/ProfileImageType.swift
Spawn-App-iOS-SwiftUI/Views/EventCardView.swift
Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/ProfileView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/BottomNavButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventParticipateButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/FriendListingView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/FriendsListView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/OpenFriendTagsView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/TagsListView.swift
Spawn-App-iOS-SwiftUI/Views/ViewModifiers/CircularButton.swift
Spawn-App-iOS-SwiftUI/Views/ViewModifiers/PlaceholderTextModifier.swift
Spawn-App-iOS-SwiftUI/Views/ViewModifiers/ProfileImages.swift

Friends List View

---

Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventTimeView.swift

Added Styling for time - currently set to white with opacity 0.05, open to change.

Added Styling for time

---

Spawn-App-iOS-SwiftUI/Views/EventCardView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventLocationView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventTimeView.swift

NOTE: styling different from figma
reason: a bit difficult to make location tag to look exactly like figma, open to change

[NEED APPROVAL] Added and altered styling to time and location

---

Spawn-App-iOS-SwiftUI/Models/FriendTag.swift
Spawn-App-iOS-SwiftUI/ViewModels/TagsListViewModel.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/Helpers/Constants.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/OpenFriendTagsView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/TagsListView.swift

just pushing my changes here first for the view tags page as I also made some changes to the overall background color etc.

part 1 of make view tags page

---

Spawn-App-iOS-SwiftUI/ViewModels/FriendsListViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/SearchViewModel.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/SearchView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/FriendListingView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/FriendsListView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/TagsSubViews/TagsListView.swift

Refactored `SearchView` into its own component, to re-use across tag & friend views.
Touched-up the tag view spacing and such:

Tag view refactoring and design adjustments

---

Spawn-App-iOS-SwiftUI/Views/Enums/ProfileImageType.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/TagsTabView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/AddTagButton.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/ColorOptions.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/ExpandedTagView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendContainer.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendRow.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/TagRow.swift
Spawn-App-iOS-SwiftUI/Views/ViewModifiers/ProfileImages.swift

Changed the following:
- AddTagButton --> added field which takes in a color, making it customizable and used it as buttons to add friends to tags; maybe rename the file name to make it more universal?
- made friends list scrollable
- resized and redesigned the whole display to mimic the figma prototype

New tags page (done re design)

---

Spawn-App-iOS-SwiftUI/Models/ChatMessage.swift
Spawn-App-iOS-SwiftUI/Models/Event.swift
Spawn-App-iOS-SwiftUI/Models/FriendTag.swift
Spawn-App-iOS-SwiftUI/Models/Location.swift
Spawn-App-iOS-SwiftUI/Models/User.swift
Spawn-App-iOS-SwiftUI/ViewModels/EventInfoViewModel.swift
Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift

This aids in my over-arching goal of connecting the front and back ends of the app, by adjusting our model classes to align with the back-end side DTOs.

Setup DTOs for API Calls

---

Spawn-App-iOS-SwiftUI.xcodeproj/project.pbxproj
Spawn-App-iOS-SwiftUI/Models/FriendTag.swift
Spawn-App-iOS-SwiftUI/Models/User.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/FriendsView.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/ColorOptions.swift

Mainly changes to the map API usage

iOS Version: 17 minimum -> 16.2

---

Spawn-App-iOS-SwiftUI/Models/User.swift
Spawn-App-iOS-SwiftUI/Spawn_App_iOS_SwiftUIApp.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift

Fixed map zoomed out too much issue + friend tags for user, `danielAgapov`

---

Spawn-App-iOS-SwiftUI/Models/User.swift
Spawn-App-iOS-SwiftUI/Spawn_App_iOS_SwiftUIApp.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/LaunchView.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/UserInfoInputView.swift
Spawn-App-iOS-SwiftUI/Views/ProfileView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/Authentication/AuthProviderButtonView.swift

- Implemented Navigation from `LaunchView` -> `UserInfoInputView` -> `FeedView` 
- Bonus Navigation: after clicking "Log Out" in `ProfileView` -> navigates to `LaunchView`
This wraps up #54

Authentication Screens: Navigation & User Input Screen

---

Spawn-App-iOS-SwiftUI/Services/API/APIError.swift
Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/Services/API/IAPIService.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/Spawn_App_iOS_SwiftUIApp.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/LaunchView.swift
Spawn-App-iOS-SwiftUI/Views/ProfileView.swift

- Created protocol (interface), error type, and instantiations of protocol for both real API fetching functionality and mocking
#50

Setup API Service for Fetching Data (+ Mock Data)

---

Spawn-App-iOS-SwiftUI/ViewModels/EventCreationViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Enums/BottomNavButtonType.swift
Spawn-App-iOS-SwiftUI/Views/EventCreationView.swift
Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventCardTopRowView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/BottomNavButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/EventCreationButtonView.swift

Event Creation View

---

Spawn-App-iOS-SwiftUI/Models/Event.swift
Spawn-App-iOS-SwiftUI/ViewModels/EventCreationViewModel.swift
Spawn-App-iOS-SwiftUI/Views/EventCreationView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventCardTopRowView.swift

`EventCreationView`, as part of #82

UI wrap up from figma

---

Spawn-App-iOS-SwiftUI/Models/DTOs/FriendRequestCreationDTO.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/FriendsTabViewModel.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/FriendsTabView.swift

- Changed hard-coded `incomingFriendRequests`, `recommendedFriends`, and `friends` to `viewModel` ones
- Added conditionals to not show sections if these arrays are empty
- Wrapped whole view in `ScrollView` to ensure nothing cuts off at top or bottom, and so scrolling is possible in case more data pops up that would take up more than screen size
- Implemented logic for recommended friend addition
- send friend request DTO to back-end (newly created `FriendRequestCreationDTO` in `/models/` here)
- Affect state for button press

Changed hard-coded values to view model ones + `ScrollView` change

---

Spawn-App-iOS-SwiftUI/Models/Event.swift
Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/Services/API/IAPIService.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/TagsViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Enums/CreationStatus.swift
Spawn-App-iOS-SwiftUI/Views/Enums/ParticipationStatus.swift
Spawn-App-iOS-SwiftUI/Views/Enums/UpsertActionType.swift
Spawn-App-iOS-SwiftUI/Views/FriendsView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/TagsTabView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/AddTagButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/ColorOptions.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/CreatingTagRowView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/ExpandedTagView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendContainer.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/TagRow.swift

- Made real post request for `FriendTag` creation to back-end
- Logic for popping out the create tag
UI progress so far:

Tags tab view logic

---

Spawn-App-iOS-SwiftUI/Models/ChatMessage.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/FriendTagCreationDTO.swift
Spawn-App-iOS-SwiftUI/Models/Event.swift
Spawn-App-iOS-SwiftUI/Models/FriendTag.swift
Spawn-App-iOS-SwiftUI/Models/User.swift
Spawn-App-iOS-SwiftUI/Services/API/APIError.swift
Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/Services/API/IAPIService.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/Event/EventCardViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/Event/EventCreationViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/FeedViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/FriendsTabViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/TagsViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/LaunchView.swift
Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/ParticipantsImagesView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/TagButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/TagsScrollView.swift

- Check if spawn user exists by external user id using endpoint `api/v1/oauth/sign-in?externalUserId`
- If yes, take to `FeedView` with that user object
- If no, proceed to onboarding, `UserInfoInputView`
- Added functionality for request params to api methods
- Made tag creation work
- Made event loading work, with LOTS of model changes & back-end 'full' DTO changes

Real spawn sign in

---

Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/Services/API/IAPIService.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/Spawn_App_iOS_SwiftUIApp.swift
Spawn-App-iOS-SwiftUI/ViewModels/FeedViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/TagsViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/UserInfoInputView.swift
Spawn-App-iOS-SwiftUI/Views/EventCardView.swift
Spawn-App-iOS-SwiftUI/Views/EventCreationView.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/FriendsView.swift
Spawn-App-iOS-SwiftUI/Views/Helpers/Constants.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift
Spawn-App-iOS-SwiftUI/Views/ProfileView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/BottomNavButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/HeaderView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Common/BackButton.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/CreatingTagRowView.swift

Getting lots of stuff from back-end instead of mock objects on mobile
- profile images for `UserInfoInputView`, `FeedView`, and `ProfileView`
- events in `FeedView`, `MapView` & `TagsTabView`
- tags in `FeedView`, `MapView` & `TagsTabView`
- user info in `ProfileView`

Final stretch api connections

---

Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/AddFriendToTagViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/Event/EventDescriptionViewModel.swift
Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
Spawn-App-iOS-SwiftUI/Views/FeedView.swift
Spawn-App-iOS-SwiftUI/Views/FriendsView.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventCreationFriendsViews/InviteTagsView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/FriendsTabView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/TagsTabView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/AddFriendToTagView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/AddTagButtonView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/ExpandedTagView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendContainer.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendRow.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/SearchView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/TagRow.swift

Add Friend To Friend Tag UI & Logic

---

Spawn-App-iOS-SwiftUI/Models/FriendRequest.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/FriendRequestViewModel.swift
Spawn-App-iOS-SwiftUI/Views/FriendRequestView.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/FriendsTabView.swift

@shannonaurl has setup the popup, and I've done the logic & API calls in this PR. Soon, Shannon will refine the UI and create a separate PR.

Friend Request Popup

---

Spawn-App-iOS-SwiftUI/Views/EventCreationView.swift
Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
Spawn-App-iOS-SwiftUI/Views/MapView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventCreationFriendsViews/InviteFriendsView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventCreationFriendsViews/InviteTagsView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/ParticipantsImagesView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/AddFriendToTagView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendRow.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/TagRow.swift

Fetch Profile Images from Back-End

---

Spawn-App-iOS-SwiftUI.xcodeproj/project.pbxproj
Spawn-App-iOS-SwiftUI/Services/KeychainService.swift
Spawn-App-iOS-SwiftUI/Spawn-App-iOS-SwiftUI.entitlements
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/LaunchView.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/UserInfoInputView.swift
Spawn-App-iOS-SwiftUI/Views/Enums/AuthProviderType.swift
Spawn-App-iOS-SwiftUI/Views/Helpers/Constants.swift
Spawn-App-iOS-SwiftUI/Views/ProfileView.swift

Apple Auth

---

Spawn-App-iOS-SwiftUI/Extensions/NotificationNameExtensions.swift
Spawn-App-iOS-SwiftUI/Info.plist
Spawn-App-iOS-SwiftUI/Models/DTOs/Notification/DeviceTokenDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/Notification/NotificationPreferencesDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/Notification/NotificationTypes.swift
Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/Services/API/IAPIService.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/Services/CustomAppDelegate.swift
Spawn-App-iOS-SwiftUI/Services/NotificationIconExporter.swift
Spawn-App-iOS-SwiftUI/Services/NotificationService.swift
Spawn-App-iOS-SwiftUI/Spawn-App-iOS-SwiftUI.entitlements
Spawn-App-iOS-SwiftUI/ViewModels/AddFriendToTagViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/Event/EventDescriptionViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/ImagePicker.swift
Spawn-App-iOS-SwiftUI/Views/Authentication/UserInfoInputView.swift
Spawn-App-iOS-SwiftUI/Views/Enums/DeleteAccountAlertType.swift
Spawn-App-iOS-SwiftUI/Views/FriendRequestView.swift
Spawn-App-iOS-SwiftUI/Views/FriendsView.swift
Spawn-App-iOS-SwiftUI/Views/ProfileView.swift
Spawn-App-iOS-SwiftUI/Views/Settings/NotificationSettingsView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/FriendsTabView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/TagsTabView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/AddFriendToTagView.swift
Spawn-App-iOS-SwiftUI/Views/SubComponents/NotificationBadgeView.swift

New notification preferences view from profile view
Bug fixes:
- #146 
- refreshing tags upon clicking off the popup to add friends to tag, to avoid disappearing tags

Notifications Preferences View + Misc. Bug Fixes

---

Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/Services/AppCache.swift
Spawn-App-iOS-SwiftUI/Services/CustomAppDelegate.swift
Spawn-App-iOS-SwiftUI/Services/NotificationService.swift

Matching back-end PR: [Cache domain #312](https://github.com/Daggerpov/Spawn-App-Back-End/pull/312)

More Caching

---

Spawn-App-iOS-SwiftUI/Info.plist
Spawn-App-iOS-SwiftUI/Views/Pages/FeedAndMap/MapView.swift

Added permissions check in `Info.plist` to enable user location tracking

Fix Map View

---

Spawn-App-iOS-SwiftUI.xcodeproj/project.pbxproj
Spawn-App-iOS-SwiftUI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Spawn-App-iOS-SwiftUI/GoogleService-Info.plist
Spawn-App-iOS-SwiftUI/Services/CustomAppDelegate.swift
Spawn-App-iOS-SwiftUI/Services/NotificationService.swift

Integration of FCM for push notifications

FCM integration

---

Spawn-App-iOS-SwiftUI/Assets.xcassets/instagram.imageset/Contents.json
Spawn-App-iOS-SwiftUI/Assets.xcassets/whatsapp.imageset/Contents.json
Spawn-App-iOS-SwiftUI/Models/DTOs/Calendar/CalendarActivityDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/BaseUserDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/UpdateUserSocialMediaDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/UserCreateDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/UserSocialMediaDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/UserStatsDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/UserUpdateDTO.swift
Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/ProfileViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Pages/Profile/EditProfileView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/Profile/ProfileView.swift

New profile design | Part 1

---

Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift

When I added the new quick sign-in functionality, I forgot to set `isLoggedIn=true` which is what was causing the bug with not actually be sent the feed page.

Fix quick sign-in

---

Spawn-App-iOS-SwiftUI/Spawn_App_iOS_SwiftUIApp.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Pages/AuthFlow/LaunchView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/AuthFlow/LoadingView.swift

- added loading screen for when auth checks are being performed

Fix signed out issue

---

Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift

Fixes loading screen bug.
Still investigating a quick-sign-in bug.

Fix quick sign in

---

Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
Spawn-App-iOS-SwiftUI/Services/AppCache.swift
Spawn-App-iOS-SwiftUI/Spawn_App_iOS_SwiftUIApp.swift
Spawn-App-iOS-SwiftUI/ViewModels/Event/DayEventsViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/FeedViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/FriendsTabViewModel.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Helpers/Constants.swift
Spawn-App-iOS-SwiftUI/Views/Pages/Events/EventCreation/SubComponents/LocationSelectionView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/FeedAndMap/MapView.swift

(Part 1) Map Time Filters & Little Fixes

---

Spawn-App-iOS-SwiftUI/Services/API/APIService.swift

Since different endpoints now return auth tokens that need to be stored, had to update iOS side to handle this

Fix auth token handling

---

Spawn-App-iOS-SwiftUI/Models/DTOs/User/AuthResponseDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/BaseUserDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/FullFriendUserDTO.swift
Spawn-App-iOS-SwiftUI/Models/DTOs/User/RecommendedFriendUserDTO.swift
Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Pages/Activities/ActivityCreation/SubComponents/InviteView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/AuthFlow/Registration/RegisterInputView.swift

I've tested each account creation and log in methods. Each appear to be working

Working registration and login

---

Spawn-App-iOS-SwiftUI/Models/DTOs/User/BaseUserDTO.swift
Spawn-App-iOS-SwiftUI/Models/Enums/SkipDestination.swift
Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Pages/AuthFlow/Greeting/WelcomeView.swift

Onboarding Skip occurs at app startup

onboarding skip at startup

---

Spawn-App-iOS-SwiftUI/Views/Helpers/Constants.swift
Spawn-App-iOS-SwiftUI/Views/Pages/Activities/ActivityCardView/ActivityCardView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/Activities/ActivityTypeCardView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/FeedAndMap/ActivityFeedView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/FeedAndMap/ActivityListView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/FeedAndMap/SubComponents/HeaderView.swift

- Updated universalSecondaryColorHexCode from colorsIndigo400 to colorsIndigo500
- Updated figmaBlack400Hex from colorsGray500 to colorsGray400
- Gave inner shadow in ActivityCardTypeView
- Increased padding in ActivityFeedView and ActivityListView for better spacing and layout consistency
- Simplified HeaderView layout

Fix: layout and styling in ActivityFeedView

---

Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
Spawn-App-iOS-SwiftUI/Views/Pages/AuthFlow/Greeting/WelcomeView.swift
Spawn-App-iOS-SwiftUI/Views/Pages/AuthFlow/Registration/UserOptionalDetailsInputView.swift

Continue onboarding
